### ISSUE TITLE
java.sql.SQLException: Illegal operation on empty result set

### ISSUE THREAD

**Issue by scofier** [BigMaMonkey/easygen#2]
`java.sql.SQLException: Illegal operation on empty result set.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:790)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5230)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5153)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5192)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.getAllPrimaryKeys(MySqlModelBuilder.java:116)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.getAllTableList(MySqlModelBuilder.java:67)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.buildDataModels(MySqlModelBuilder.java:31)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.buildDataModels(MySqlModelBuilder.java:15)
	at org.bigmamonkey.core.GeneratorManager.Start(GeneratorManager.java:88)
	at org.bigmamonkey.App.main(App.java:12)`

**Comment by scofier** [comment]
`String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at org.bigmamonkey.util.StringUtil.ToUpperName(StringUtil.java:20)
	at org.bigmamonkey.modelBuilder.TableField.setName(TableField.java:25)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.getTableFields(MySqlModelBuilder.java:99)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.getAllTableList(MySqlModelBuilder.java:66)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.buildDataModels(MySqlModelBuilder.java:31)
	at org.bigmamonkey.modelBuilder.MySqlModelBuilder.buildDataModels(MySqlModelBuilder.java:15)
	at org.bigmamonkey.core.GeneratorManager.Start(GeneratorManager.java:88)
	at org.bigmamonkey.App.main(App.java:12)`

**Comment by SureChang** [comment]
@scofier 原因可能是目标表没有主键 getAllPrimaryKeys 加个主键试一试，我会加个判断，修复这个问题

**Comment by scofier** [comment]
@BigMaMonkey  好， 第二个问题是有些表是下划线“_”开头的 比如： _id ,_op_time

**Comment by SureChang** [comment]
@scofier 明白了 我马上改一下，改好@你

**Comment by SureChang** [comment]
@scofier i fixed it in  [v0.0.3](https://github.com/BigMaMonkey/easygen/releases/tag/v0.0.3)

**Comment by SureChang** [comment]
i fixed it in v0.0.3 releases
